// 全世界国家/地区列表（ISO 3166-1 alpha-2 + 简中 + 英文 + 大洲）。
// 用户注册时从下拉自选国家（必填）。后续增改只动这个数组，重启即生效。
export interface Country {
  code: string
  zh: string
  en: string
  region: string // 亚洲/欧洲/非洲/北美洲/南美洲/大洋洲
}

export const COUNTRIES: Country[] = [
  // —— 亚洲 ——
  { code: 'CN', zh: '中国', en: 'China', region: '亚洲' },
  { code: 'HK', zh: '中国香港', en: 'Hong Kong', region: '亚洲' },
  { code: 'TW', zh: '中国台湾', en: 'Taiwan', region: '亚洲' },
  { code: 'MO', zh: '中国澳门', en: 'Macau', region: '亚洲' },
  { code: 'JP', zh: '日本', en: 'Japan', region: '亚洲' },
  { code: 'KR', zh: '韩国', en: 'South Korea', region: '亚洲' },
  { code: 'KP', zh: '朝鲜', en: 'North Korea', region: '亚洲' },
  { code: 'MN', zh: '蒙古', en: 'Mongolia', region: '亚洲' },
  { code: 'IN', zh: '印度', en: 'India', region: '亚洲' },
  { code: 'PK', zh: '巴基斯坦', en: 'Pakistan', region: '亚洲' },
  { code: 'BD', zh: '孟加拉国', en: 'Bangladesh', region: '亚洲' },
  { code: 'NP', zh: '尼泊尔', en: 'Nepal', region: '亚洲' },
  { code: 'BT', zh: '不丹', en: 'Bhutan', region: '亚洲' },
  { code: 'LK', zh: '斯里兰卡', en: 'Sri Lanka', region: '亚洲' },
  { code: 'MV', zh: '马尔代夫', en: 'Maldives', region: '亚洲' },
  { code: 'AF', zh: '阿富汗', en: 'Afghanistan', region: '亚洲' },
  { code: 'KZ', zh: '哈萨克斯坦', en: 'Kazakhstan', region: '亚洲' },
  { code: 'KG', zh: '吉尔吉斯斯坦', en: 'Kyrgyzstan', region: '亚洲' },
  { code: 'TJ', zh: '塔吉克斯坦', en: 'Tajikistan', region: '亚洲' },
  { code: 'UZ', zh: '乌兹别克斯坦', en: 'Uzbekistan', region: '亚洲' },
  { code: 'TM', zh: '土库曼斯坦', en: 'Turkmenistan', region: '亚洲' },
  { code: 'AZ', zh: '阿塞拜疆', en: 'Azerbaijan', region: '亚洲' },
  { code: 'GE', zh: '格鲁吉亚', en: 'Georgia', region: '亚洲' },
  { code: 'AM', zh: '亚美尼亚', en: 'Armenia', region: '亚洲' },
  { code: 'TR', zh: '土耳其', en: 'Turkey', region: '亚洲' },
  { code: 'CY', zh: '塞浦路斯', en: 'Cyprus', region: '亚洲' },
  { code: 'SY', zh: '叙利亚', en: 'Syria', region: '亚洲' },
  { code: 'LB', zh: '黎巴嫩', en: 'Lebanon', region: '亚洲' },
  { code: 'IL', zh: '以色列', en: 'Israel', region: '亚洲' },
  { code: 'PS', zh: '巴勒斯坦', en: 'Palestine', region: '亚洲' },
  { code: 'JO', zh: '约旦', en: 'Jordan', region: '亚洲' },
  { code: 'IQ', zh: '伊拉克', en: 'Iraq', region: '亚洲' },
  { code: 'IR', zh: '伊朗', en: 'Iran', region: '亚洲' },
  { code: 'SA', zh: '沙特阿拉伯', en: 'Saudi Arabia', region: '亚洲' },
  { code: 'AE', zh: '阿联酋', en: 'United Arab Emirates', region: '亚洲' },
  { code: 'KW', zh: '科威特', en: 'Kuwait', region: '亚洲' },
  { code: 'QA', zh: '卡塔尔', en: 'Qatar', region: '亚洲' },
  { code: 'BH', zh: '巴林', en: 'Bahrain', region: '亚洲' },
  { code: 'OM', zh: '阿曼', en: 'Oman', region: '亚洲' },
  { code: 'YE', zh: '也门', en: 'Yemen', region: '亚洲' },
  { code: 'SG', zh: '新加坡', en: 'Singapore', region: '亚洲' },
  { code: 'MY', zh: '马来西亚', en: 'Malaysia', region: '亚洲' },
  { code: 'TH', zh: '泰国', en: 'Thailand', region: '亚洲' },
  { code: 'VN', zh: '越南', en: 'Vietnam', region: '亚洲' },
  { code: 'ID', zh: '印度尼西亚', en: 'Indonesia', region: '亚洲' },
  { code: 'PH', zh: '菲律宾', en: 'Philippines', region: '亚洲' },
  { code: 'KH', zh: '柬埔寨', en: 'Cambodia', region: '亚洲' },
  { code: 'MM', zh: '缅甸', en: 'Myanmar', region: '亚洲' },
  { code: 'LA', zh: '老挝', en: 'Laos', region: '亚洲' },
  { code: 'BN', zh: '文莱', en: 'Brunei', region: '亚洲' },
  { code: 'TL', zh: '东帝汶', en: 'Timor-Leste', region: '亚洲' },

  // —— 欧洲 ——
  { code: 'GB', zh: '英国', en: 'United Kingdom', region: '欧洲' },
  { code: 'IE', zh: '爱尔兰', en: 'Ireland', region: '欧洲' },
  { code: 'FR', zh: '法国', en: 'France', region: '欧洲' },
  { code: 'DE', zh: '德国', en: 'Germany', region: '欧洲' },
  { code: 'NL', zh: '荷兰', en: 'Netherlands', region: '欧洲' },
  { code: 'BE', zh: '比利时', en: 'Belgium', region: '欧洲' },
  { code: 'LU', zh: '卢森堡', en: 'Luxembourg', region: '欧洲' },
  { code: 'CH', zh: '瑞士', en: 'Switzerland', region: '欧洲' },
  { code: 'AT', zh: '奥地利', en: 'Austria', region: '欧洲' },
  { code: 'LI', zh: '列支敦士登', en: 'Liechtenstein', region: '欧洲' },
  { code: 'IT', zh: '意大利', en: 'Italy', region: '欧洲' },
  { code: 'ES', zh: '西班牙', en: 'Spain', region: '欧洲' },
  { code: 'PT', zh: '葡萄牙', en: 'Portugal', region: '欧洲' },
  { code: 'GR', zh: '希腊', en: 'Greece', region: '欧洲' },
  { code: 'MT', zh: '马耳他', en: 'Malta', region: '欧洲' },
  { code: 'DK', zh: '丹麦', en: 'Denmark', region: '欧洲' },
  { code: 'SE', zh: '瑞典', en: 'Sweden', region: '欧洲' },
  { code: 'NO', zh: '挪威', en: 'Norway', region: '欧洲' },
  { code: 'FI', zh: '芬兰', en: 'Finland', region: '欧洲' },
  { code: 'IS', zh: '冰岛', en: 'Iceland', region: '欧洲' },
  { code: 'PL', zh: '波兰', en: 'Poland', region: '欧洲' },
  { code: 'CZ', zh: '捷克', en: 'Czechia', region: '欧洲' },
  { code: 'SK', zh: '斯洛伐克', en: 'Slovakia', region: '欧洲' },
  { code: 'HU', zh: '匈牙利', en: 'Hungary', region: '欧洲' },
  { code: 'RO', zh: '罗马尼亚', en: 'Romania', region: '欧洲' },
  { code: 'BG', zh: '保加利亚', en: 'Bulgaria', region: '欧洲' },
  { code: 'UA', zh: '乌克兰', en: 'Ukraine', region: '欧洲' },
  { code: 'BY', zh: '白俄罗斯', en: 'Belarus', region: '欧洲' },
  { code: 'RU', zh: '俄罗斯', en: 'Russia', region: '欧洲' },
  { code: 'MD', zh: '摩尔多瓦', en: 'Moldova', region: '欧洲' },
  { code: 'LT', zh: '立陶宛', en: 'Lithuania', region: '欧洲' },
  { code: 'LV', zh: '拉脱维亚', en: 'Latvia', region: '欧洲' },
  { code: 'EE', zh: '爱沙尼亚', en: 'Estonia', region: '欧洲' },
  { code: 'RS', zh: '塞尔维亚', en: 'Serbia', region: '欧洲' },
  { code: 'HR', zh: '克罗地亚', en: 'Croatia', region: '欧洲' },
  { code: 'SI', zh: '斯洛文尼亚', en: 'Slovenia', region: '欧洲' },
  { code: 'BA', zh: '波黑', en: 'Bosnia and Herzegovina', region: '欧洲' },
  { code: 'ME', zh: '黑山', en: 'Montenegro', region: '欧洲' },
  { code: 'MK', zh: '北马其顿', en: 'North Macedonia', region: '欧洲' },
  { code: 'AL', zh: '阿尔巴尼亚', en: 'Albania', region: '欧洲' },
  { code: 'MC', zh: '摩纳哥', en: 'Monaco', region: '欧洲' },
  { code: 'SM', zh: '圣马力诺', en: 'San Marino', region: '欧洲' },
  { code: 'VA', zh: '梵蒂冈', en: 'Vatican City', region: '欧洲' },
  { code: 'AD', zh: '安道尔', en: 'Andorra', region: '欧洲' },

  // —— 非洲 ——
  { code: 'EG', zh: '埃及', en: 'Egypt', region: '非洲' },
  { code: 'LY', zh: '利比亚', en: 'Libya', region: '非洲' },
  { code: 'TN', zh: '突尼斯', en: 'Tunisia', region: '非洲' },
  { code: 'DZ', zh: '阿尔及利亚', en: 'Algeria', region: '非洲' },
  { code: 'MA', zh: '摩洛哥', en: 'Morocco', region: '非洲' },
  { code: 'SD', zh: '苏丹', en: 'Sudan', region: '非洲' },
  { code: 'SS', zh: '南苏丹', en: 'South Sudan', region: '非洲' },
  { code: 'ET', zh: '埃塞俄比亚', en: 'Ethiopia', region: '非洲' },
  { code: 'ER', zh: '厄立特里亚', en: 'Eritrea', region: '非洲' },
  { code: 'DJ', zh: '吉布提', en: 'Djibouti', region: '非洲' },
  { code: 'SO', zh: '索马里', en: 'Somalia', region: '非洲' },
  { code: 'KE', zh: '肯尼亚', en: 'Kenya', region: '非洲' },
  { code: 'UG', zh: '乌干达', en: 'Uganda', region: '非洲' },
  { code: 'TZ', zh: '坦桑尼亚', en: 'Tanzania', region: '非洲' },
  { code: 'RW', zh: '卢旺达', en: 'Rwanda', region: '非洲' },
  { code: 'BI', zh: '布隆迪', en: 'Burundi', region: '非洲' },
  { code: 'CD', zh: '刚果（金）', en: 'DR Congo', region: '非洲' },
  { code: 'CG', zh: '刚果（布）', en: 'Republic of the Congo', region: '非洲' },
  { code: 'GA', zh: '加蓬', en: 'Gabon', region: '非洲' },
  { code: 'GQ', zh: '赤道几内亚', en: 'Equatorial Guinea', region: '非洲' },
  { code: 'CM', zh: '喀麦隆', en: 'Cameroon', region: '非洲' },
  { code: 'CF', zh: '中非', en: 'Central African Republic', region: '非洲' },
  { code: 'TD', zh: '乍得', en: 'Chad', region: '非洲' },
  { code: 'NE', zh: '尼日尔', en: 'Niger', region: '非洲' },
  { code: 'NG', zh: '尼日利亚', en: 'Nigeria', region: '非洲' },
  { code: 'BJ', zh: '贝宁', en: 'Benin', region: '非洲' },
  { code: 'TG', zh: '多哥', en: 'Togo', region: '非洲' },
  { code: 'GH', zh: '加纳', en: 'Ghana', region: '非洲' },
  { code: 'CI', zh: '科特迪瓦', en: "Côte d'Ivoire", region: '非洲' },
  { code: 'LR', zh: '利比里亚', en: 'Liberia', region: '非洲' },
  { code: 'SL', zh: '塞拉利昂', en: 'Sierra Leone', region: '非洲' },
  { code: 'GN', zh: '几内亚', en: 'Guinea', region: '非洲' },
  { code: 'GW', zh: '几内亚比绍', en: 'Guinea-Bissau', region: '非洲' },
  { code: 'SN', zh: '塞内加尔', en: 'Senegal', region: '非洲' },
  { code: 'GM', zh: '冈比亚', en: 'Gambia', region: '非洲' },
  { code: 'ML', zh: '马里', en: 'Mali', region: '非洲' },
  { code: 'BF', zh: '布基纳法索', en: 'Burkina Faso', region: '非洲' },
  { code: 'MR', zh: '毛里塔尼亚', en: 'Mauritania', region: '非洲' },
  { code: 'CV', zh: '佛得角', en: 'Cabo Verde', region: '非洲' },
  { code: 'ST', zh: '圣多美和普林西比', en: 'São Tomé and Príncipe', region: '非洲' },
  { code: 'ZA', zh: '南非', en: 'South Africa', region: '非洲' },
  { code: 'NA', zh: '纳米比亚', en: 'Namibia', region: '非洲' },
  { code: 'BW', zh: '博茨瓦纳', en: 'Botswana', region: '非洲' },
  { code: 'ZW', zh: '津巴布韦', en: 'Zimbabwe', region: '非洲' },
  { code: 'ZM', zh: '赞比亚', en: 'Zambia', region: '非洲' },
  { code: 'MW', zh: '马拉维', en: 'Malawi', region: '非洲' },
  { code: 'MZ', zh: '莫桑比克', en: 'Mozambique', region: '非洲' },
  { code: 'MG', zh: '马达加斯加', en: 'Madagascar', region: '非洲' },
  { code: 'KM', zh: '科摩罗', en: 'Comoros', region: '非洲' },
  { code: 'SC', zh: '塞舌尔', en: 'Seychelles', region: '非洲' },
  { code: 'MU', zh: '毛里求斯', en: 'Mauritius', region: '非洲' },
  { code: 'LS', zh: '莱索托', en: 'Lesotho', region: '非洲' },
  { code: 'SZ', zh: '斯威士兰', en: 'Eswatini', region: '非洲' },
  { code: 'AO', zh: '安哥拉', en: 'Angola', region: '非洲' },

  // —— 北美洲 ——
  { code: 'US', zh: '美国', en: 'United States', region: '北美洲' },
  { code: 'CA', zh: '加拿大', en: 'Canada', region: '北美洲' },
  { code: 'MX', zh: '墨西哥', en: 'Mexico', region: '北美洲' },
  { code: 'GT', zh: '危地马拉', en: 'Guatemala', region: '北美洲' },
  { code: 'BZ', zh: '伯利兹', en: 'Belize', region: '北美洲' },
  { code: 'SV', zh: '萨尔瓦多', en: 'El Salvador', region: '北美洲' },
  { code: 'HN', zh: '洪都拉斯', en: 'Honduras', region: '北美洲' },
  { code: 'NI', zh: '尼加拉瓜', en: 'Nicaragua', region: '北美洲' },
  { code: 'CR', zh: '哥斯达黎加', en: 'Costa Rica', region: '北美洲' },
  { code: 'PA', zh: '巴拿马', en: 'Panama', region: '北美洲' },
  { code: 'CU', zh: '古巴', en: 'Cuba', region: '北美洲' },
  { code: 'JM', zh: '牙买加', en: 'Jamaica', region: '北美洲' },
  { code: 'HT', zh: '海地', en: 'Haiti', region: '北美洲' },
  { code: 'DO', zh: '多米尼加', en: 'Dominican Republic', region: '北美洲' },
  { code: 'BS', zh: '巴哈马', en: 'Bahamas', region: '北美洲' },
  { code: 'BB', zh: '巴巴多斯', en: 'Barbados', region: '北美洲' },
  { code: 'TT', zh: '特立尼达和多巴哥', en: 'Trinidad and Tobago', region: '北美洲' },

  // —— 南美洲 ——
  { code: 'BR', zh: '巴西', en: 'Brazil', region: '南美洲' },
  { code: 'AR', zh: '阿根廷', en: 'Argentina', region: '南美洲' },
  { code: 'CL', zh: '智利', en: 'Chile', region: '南美洲' },
  { code: 'PE', zh: '秘鲁', en: 'Peru', region: '南美洲' },
  { code: 'CO', zh: '哥伦比亚', en: 'Colombia', region: '南美洲' },
  { code: 'VE', zh: '委内瑞拉', en: 'Venezuela', region: '南美洲' },
  { code: 'EC', zh: '厄瓜多尔', en: 'Ecuador', region: '南美洲' },
  { code: 'BO', zh: '玻利维亚', en: 'Bolivia', region: '南美洲' },
  { code: 'PY', zh: '巴拉圭', en: 'Paraguay', region: '南美洲' },
  { code: 'UY', zh: '乌拉圭', en: 'Uruguay', region: '南美洲' },
  { code: 'GY', zh: '圭亚那', en: 'Guyana', region: '南美洲' },
  { code: 'SR', zh: '苏里南', en: 'Suriname', region: '南美洲' },

  // —— 大洋洲 ——
  { code: 'AU', zh: '澳大利亚', en: 'Australia', region: '大洋洲' },
  { code: 'NZ', zh: '新西兰', en: 'New Zealand', region: '大洋洲' },
  { code: 'PG', zh: '巴布亚新几内亚', en: 'Papua New Guinea', region: '大洋洲' },
  { code: 'FJ', zh: '斐济', en: 'Fiji', region: '大洋洲' },
  { code: 'SB', zh: '所罗门群岛', en: 'Solomon Islands', region: '大洋洲' },
  { code: 'VU', zh: '瓦努阿图', en: 'Vanuatu', region: '大洋洲' },
  { code: 'WS', zh: '萨摩亚', en: 'Samoa', region: '大洋洲' },
  { code: 'TO', zh: '汤加', en: 'Tonga', region: '大洋洲' },
  { code: 'FM', zh: '密克罗尼西亚', en: 'Micronesia', region: '大洋洲' },
  { code: 'MH', zh: '马绍尔群岛', en: 'Marshall Islands', region: '大洋洲' },
  { code: 'PW', zh: '帕劳', en: 'Palau', region: '大洋洲' },
  { code: 'KI', zh: '基里巴斯', en: 'Kiribati', region: '大洋洲' },
  { code: 'NR', zh: '瑙鲁', en: 'Nauru', region: '大洋洲' },
  { code: 'TV', zh: '图瓦卢', en: 'Tuvalu', region: '大洋洲' },
]
